# Deployment web application Kube-news

apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-temp
  template:
    metadata:
      labels:
        app: conv-temp
    spec:
      containers:
      - name: conv-temp
        image: danielbombonate/conversao-temperatura:v1
---
apiVersion: v1
kind: Service
metadata:
  name: conv-temp
spec:
  selector:
    app: conv-temp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort

